In [530]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [531]:
df =pd.read_csv('dataset/Realistic_Messy_Employee_Dataset_Beginner_Friendly.csv')
df

,ID,Name,Age,Gender,Email,Phone_Number,City,Department,Salary,Joining_Date,Experience_Years,Performance_Score,Manager_ID,Work_Location,Bonus_Percentage,Remote_Onsite
0,16271,Morgan Reyes,39,NaN,santanaheidi@simpson.com,862.555.7437x566,delhi,Financ,104695.6,2019-05-09,12.0,1,10002.0,Chennai,18.0,Onsite
1,12235,Brendan Thomas,31,NaN,anthony69@hotmail.com,001-080-715-5689x268,Chennai,Financ,146215,2017-12-17,16.0,5,10018.0,Hyderabad,29.0,onsite
2,10743,Jeanette Hooper,41,M,gutierrezzachary@gmail.com,1139018681,Bangalore,IT,124286,2018-02-08,2.0,Good,10071.0,Delhi,22.0,remote
3,19229,Jesse Stewart,39,NaN,kmartinez@hotmail.com,+1-108-550-5011x4112,delhi,IT,111413,2018-04-07,14.0,Poor,10042.0,NaN,29.0,Remote
4,12385,William Maxwell,19,Male,shortjay@abc.org,050.572.6766,delhi,Financ,99001,2024-10-19,11.0,NaN,10094.0,Bangalore,16.0,onsite
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6076,18150,Kevin Campbell,24,female,marcowright@gmail.com,001-662-677-1946x18388,mumbai,Finance,148166,2021-11-16,5.0,Poor,10020.0,Hyderabad,29.0,Onsite
6077,15492,Richard Garcia,37,male,wgonzalez@yahoo.com,003.857.8489x4984,Bangalore,HR,41558,2021-03-08,3.0,2,10082.0,Bangalor,27.0,Hybrid
6078,18233,Richard Rodriguez,48,NaN,wrose@ortiz-wong.com,001-311-370-6322x0556,Chennai,HR,39682,2023-06-08,20.0,3,10071.0,Hyderabad,27.0,remote
6079,14157,Lucas Ramsey,18,NaN,cgreen@peters-reyes.info,326.539.9841,Mmbai,NaN,127574.42,2024-06-16,9.0,Poor,10024.0,Mmbai,1.0,Remote
6080,10656,Leslie Hansen,21,NaN,j,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [532]:
missing = df.isnull().sum().sort_values(ascending=False)
missing_percent = (missing / len(df)) * 100

pd.DataFrame({'Missing Values': missing, 'Percentage': missing_percent})

                   Missing Values  Percentage
Remote_Onsite                1020   16.773557
Gender                        784   12.892616
Work_Location                 735   12.086828
Performance_Score             668   10.985035
City                          596    9.801020
Department                    535    8.797895
Bonus_Percentage              131    2.154251
Name                          125    2.055583
Joining_Date                  111    1.825358
Phone_Number                   77    1.266239
Manager_ID                     69    1.134682
Email                          66    1.085348
Experience_Years               64    1.052458
Age                            61    1.003124
Salary                         55    0.904457
ID                              0    0.000000

In [533]:
df.duplicated().sum()

np.int64(6)

In [534]:
df.drop_duplicates(inplace=True)

In [535]:
df.dtypes

ID                     int64
Name                  object
Age                   object
Gender                object
Email                 object
Phone_Number          object
City                  object
Department            object
Salary                object
Joining_Date          object
Experience_Years     float64
Performance_Score     object
Manager_ID           float64
Work_Location         object
Bonus_Percentage     float64
Remote_Onsite         object
dtype: object

In [536]:
df['Name'].isnull().sum()

np.int64(124)

In [537]:
df['Name'].head()

0       Morgan Reyes
1     Brendan Thomas
2    Jeanette Hooper
3      Jesse Stewart
4    William Maxwell
Name: Name, dtype: object

In [538]:
# df['column_name'] = df['column_name'].str.strip().str.replace(r'\s+', ' ', regex=True)

In [539]:
extra_spaces_names = df[df['Name'].str.startswith(' ')|df['Name'].str.endswith(' ')]
extra_spaces_names

,ID,Name,Age,Gender,Email,Phone_Number,City,Department,Salary,Joining_Date,Experience_Years,Performance_Score,Manager_ID,Work_Location,Bonus_Percentage,Remote_Onsite
196,17080,Jerry Ellis,37,male,sandracarter@gregory.org,755-653-0679x08707,Chennai,Operations,79245,2022-12-30,2.0,Good,10018.0,Mumbai,20.0,remote
386,11304,Brittany Avery,62,Male,nancy35@torres.com,248-069-6628x264,Hyderabad,sales,69037,2023-05-30,10.0,5,10003.0,NaN,1.0,onsite
402,12983,Kristen Mccormick,39,Female,jason12@gmail.com,658.594.2860,Bangalor,Marketing,4943155,2018-07-26,17.0,5,10056.0,Mmbai,17.0,NaN
430,15095,Vincent Franco,NaN,male,james01@miller-valencia.info,+1-581-351-9496,Mumbai,Finance,105733.3,2017-03-29,3.0,4,10059.0,Mmbai,13.0,Remote
433,14276,Jill Jones,55,Female,arthurallen@barry.com,+1-795-496-4059x322,Bangalore,HR,136017,2020-11-05,9.0,1,10096.0,Hyderabad,29.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5926,12380,Mike Hawkins,twenty,female,jamesarnold@hotmail.com,5526582771,Delhi,hr,81827,2018-05-27,19.0,Excellent,10028.0,Delhi,11.0,Onsite
5980,19651,William Soto,35,Male,hmurphy@patterson-cisneros.com,001-312-760-1682x14507,Hyderabad,IT,149547,2022-09-21,5.0,Excellent,10016.0,Mmbai,10.0,remote
6002,18306,Amanda Rocha,22,Female,igonzalez@hotmail.com,001-390-092-3546x147,Bangalore,Sales,4667817,2017-08-20,9.0,Poor,10057.0,Mumbai,19.0,remote
6026,14886,Rachel Shaw,forty-five,male,lambertandre@vance-mcpherson.biz,(645)117-5591x893,mumbai,sales,NaN,2020-10-27,4.0,1,10014.0,Bangalor,16.0,Remote
6044,13764,Amber Lee,18,NaN,user#domain.com,534.668.7825x656,NaN,IT,122470,2019-08-20,7.0,4,10069.0,Hyderabad,30.0,Hybrid

In [540]:
print('Total names with extra spaces:', len(extra_spaces_names))

Total names with extra spaces: 126

In [541]:
import re

# Function to check for special characters in names
def has_special_characters(name):
    if pd.isnull(name):
        return False
    return bool(re.search(r'[^a-zA-Z\s]', name))

special_char_names = df[df['Name'].apply(has_special_characters)]
special_char_names.head(20)

,ID,Name,Age,Gender,Email,Phone_Number,City,Department,Salary,Joining_Date,Experience_Years,Performance_Score,Manager_ID,Work_Location,Bonus_Percentage,Remote_Onsite
87,16021,Dr. Phillip Austin,20,female,richardjones@gmail.com,368.326.6659x394,Mumbai,Sales,93125,"Oct 27, 2024",15.0,3,10061.0,Hyderabad,30.0,Onsite
132,17459,Scott Bates Jr.,62,Male,fordgerald@yahoo.com,+1-103-135-1436,mumbai,HR,44204,2024-11-26,12.0,1,10016.0,Mmbai,10.0,Remote
177,16971,Mr. Fernando Pena DVM,26,male,caineric@rodriguez.com,001-707-292-9713x59237,Bangalor,HR,62535,2025-07-15,4.0,NaN,88888.0,Hyderabad,19.0,remote
254,12704,Mr. Philip Webb,61,female,hermankyle@santiago-green.org,+1-568-666-0363x473,Mmbai,Operations,129427,2025-12-28,7.0,Good,10033.0,Mumbai,-10.0,Hybrid
275,13053,Perry Villegas Jr.,60,Female,jeremy15@copeland.biz,001-507-697-8881x08694,Hyderabad,Marketing,116321,2023-12-19,6.0,5,10006.0,Mmbai,14.0,Hybrid
290,19378,Mr. Patrick Bennett Jr.,54,NaN,tflynn@underwood.info,(768)352-6971x361,Mumbai,IT,95241,2017-04-26,30.0,1,10047.0,Mmbai,29.0,Remote
292,16585,Mrs. Cindy Maldonado,29,female,camposnicole@yahoo.com,837-199-2031,Hyderabad,Sales,129835,2016-04-03,16.0,Excellent,10040.0,Mumbai,27.0,NaN
320,16871,Dr. Maurice Beasley DDS,-20,NaN,robert70@hughes-ramirez.com,1566126900,Mmbai,hr,98953,2024-08-02,0.0,2,10078.0,Mumbai,28.0,Hybrid
321,17013,Mr. Dwayne Perez,44,Male,sydney59@gmail.com,771.637.4753,NaN,Operations,30340,2024-10-23,20.0,1,10026.0,Mmbai,25.0,Hybrid
411,12235,Dr. James Fisher,18,NaN,brandon73@gutierrez.org,755.948.0608x8724,Delhi,sales,64667.1,2021-07-14,20.0,Poor,10047.0,Mmbai,4.0,onsite
421,17532,Dr. Monica Franklin,33,female,elizabethhancock@lee.com,290-436-3649x7982,Hyderabad,Finance,145212,2020-07-06,12.0,Excellent,10070.0,NaN,3.0,Hybrid
429,11524,Mr. Steven Miller,35,Male,vsmith@hotmail.com,(974)449-9861x6474,Mmbai,Marketing,44592.31,2025-12-13,2.0,NaN,10029.0,NaN,22.0,Remote
465,15460,Mrs. Diana Robinson,48.8,male,annettesmith@yahoo.com,(091)045-6766x531,mumbai,Financ,102509,2024-08-16,12.0,Poor,10018.0,Delhi,6.0,Remote
527,16745,Mr. Evan Byrd,61,Male,philipreyes@gallagher.org,880-377-1079,Mumbai,NaN,120636,2024-01-20,16.0,2,10063.0,Chennai,3.0,Hybrid
550,16769,Mrs. Katrina Pearson,24,M,zharrington@roberts.org,571-272-1937x21713,Chennai,Sales,101580,2023-01-10,25.0,2,10049.0,Delhi,18.0,Onsite
579,12160,Dr. Laurie Nguyen,thirty-two,Female,jarnold@wright-king.biz,(924)322-3135,Bangalor,sales,76833,2016-10-16,12.0,Good,10001.0,Hyderabad,18.0,Remote
645,13145,Walter Flores Jr.,65,female,brian59@rojas.com,(625)865-7933,mumbai,IT,79747.41,2025-01-15,17.0,4,10034.0,Mmbai,1.0,onsite
732,11005,Mrs. Yvonne Chavez,43,M,hcarpenter@osborne-miranda.net,601-053-3229,Mumbai,NaN,61491,2017-08-12,18.0,NaN,10067.0,NaN,128.0,remote
781,15776,Mr. Allen Murray,34,female,udennis@gmail.com,001-321-328-6144x8433,Mmbai,Operations,131883,2017-08-19,13.0,4,88888.0,Chennai,30.0,onsite
809,15900,Dr. Michael Gonzalez,64,M,timothy95@wade-barrera.biz,620-093-8778x019,Mumbai,HR,40239,2020-05-01,17.0,4,10069.0,Delhi,NaN,Hybrid

In [542]:
print(f"Number of entries with extra spaces in 'Name': {len(extra_spaces_names)}")

Number of entries with extra spaces in 'Name': 126

In [543]:
df['Name'] = df['Name'].fillna('Unknown')
df['Name']

0            Morgan Reyes
1          Brendan Thomas
2         Jeanette Hooper
3           Jesse Stewart
4         William Maxwell
              ...
6076       Kevin Campbell
6077       Richard Garcia
6078    Richard Rodriguez
6079         Lucas Ramsey
6080        Leslie Hansen
Name: Name, Length: 6075, dtype: object

In [544]:
df['Name'] = df['Name'].astype(str).str.strip()
df['Name']

0            Morgan Reyes
1          Brendan Thomas
2         Jeanette Hooper
3           Jesse Stewart
4         William Maxwell
              ...
6076       Kevin Campbell
6077       Richard Garcia
6078    Richard Rodriguez
6079         Lucas Ramsey
6080        Leslie Hansen
Name: Name, Length: 6075, dtype: object

In [545]:
df['Name'] = df['Name'].replace('Morgan Reyes', 'Morgan #@Reyes')
df['Name']

0          Morgan #@Reyes
1          Brendan Thomas
2         Jeanette Hooper
3           Jesse Stewart
4         William Maxwell
              ...
6076       Kevin Campbell
6077       Richard Garcia
6078    Richard Rodriguez
6079         Lucas Ramsey
6080        Leslie Hansen
Name: Name, Length: 6075, dtype: object

In [546]:
df['Name'] = df['Name'].apply(lambda x: re.sub(r'[^a-zA-Z\s]', '', x))
df['Name']

0            Morgan Reyes
1          Brendan Thomas
2         Jeanette Hooper
3           Jesse Stewart
4         William Maxwell
              ...
6076       Kevin Campbell
6077       Richard Garcia
6078    Richard Rodriguez
6079         Lucas Ramsey
6080        Leslie Hansen
Name: Name, Length: 6075, dtype: object

In [547]:
df['Name'] = df['Name'].str.title()
df['Name'].isnull().sum()
df['Name']

0            Morgan Reyes
1          Brendan Thomas
2         Jeanette Hooper
3           Jesse Stewart
4         William Maxwell
              ...
6076       Kevin Campbell
6077       Richard Garcia
6078    Richard Rodriguez
6079         Lucas Ramsey
6080        Leslie Hansen
Name: Name, Length: 6075, dtype: object

In [548]:
df['Age'].unique()

array(['39', '31', '41', '19', '56', '62', '63', '20', '51', '38', '33',
       '53', '44', '48', '26', '43', '47', '28', '40', '35', '55', '42',
       'forty-five', '54', '64', '29.2', '57', '32', '27', '37', '25',
       '21', '30', '29', '18', 'twenty', '59', '34', '61', '22', '49',
       '58', '24', '65', '46', '200', '60', '36', '50', '27.4', '45', nan,
       '150', '52', '39.5', '23', '33.5', '-20', '34.7', '48.8', '101',
       '-5', 'thirty-two', '-1', '56.3', '38.1', '35.1', '56.6', '60.4',
       '25.4', '22.4', '59.2', '38.3', '34.3', '21.4', '59.0', '52.7',
       '40.1', '64.8', '33.1', '40.2', '54.5', '47.8', '27.8', '22.9',
       '34.2', '21.3', '38.0', '59.9', '18.6', '25.6', '23.0', '41.9',
       '44.1', '64.3', '47.2', '29.1', '24.7', '37.1', '34.1', '25.5',
       '55.3', '33.0', '52.9', '21.8', '56.1', '58.2', '53.0', '56.4'],
      dtype=object)

In [549]:
missing_count = df['Age'].isnull().sum()
print('Missing values in Age; ', missing_count)

Missing values in Age;  61

In [550]:
df['Age'] = df['Age'].astype(str)

In [551]:
def contains_letters(age_value):
    if age_value.lower() == 'nan':  # skip nan
        return False
    return any(char.isalpha() for char in age_value) # True if any character is a letter

In [552]:
Age_has_letters = df['Age'].apply(contains_letters)
Age_has_letters

0       False
1       False
2       False
3       False
4       False
        ...
6076    False
6077    False
6078    False
6079    False
6080    False
Name: Age, Length: 6075, dtype: bool

In [553]:
non_numeric_age = df[Age_has_letters]
non_numeric_age['Age'].value_counts

<bound method IndexOpsMixin.value_counts of 30      forty-five
53          twenty
256     forty-five
294     forty-five
356         twenty
           ...
5756    thirty-two
5926        twenty
6020    forty-five
6026    forty-five
6043    thirty-two
Name: Age, Length: 61, dtype: object>

In [554]:
non_numeric_age['Age'].unique()

array(['forty-five', 'twenty', 'thirty-two'], dtype=object)

In [555]:
df['Age'] = df['Age'].replace(['forty-five', 'twenty', 'thirty-two'],['45','20','32'])
df['Age'] = df['Age'].replace('nan',np.nan)

In [556]:
df['Age'] = pd.to_numeric(df['Age'], errors = 'coerce')
negative_age =df[df['Age']<0]

In [557]:
negative_age['Age'].value_counts()

Age
-1.0     21
-20.0    16
-5.0     16
Name: count, dtype: int64

In [558]:
df['Age'] = df['Age'].where(df['Age'] >= 0,np.nan)

In [559]:
df[df['Age']>=0]

,ID,Name,Age,Gender,Email,Phone_Number,City,Department,Salary,Joining_Date,Experience_Years,Performance_Score,Manager_ID,Work_Location,Bonus_Percentage,Remote_Onsite
0,16271,Morgan Reyes,39.0,NaN,santanaheidi@simpson.com,862.555.7437x566,delhi,Financ,104695.6,2019-05-09,12.0,1,10002.0,Chennai,18.0,Onsite
1,12235,Brendan Thomas,31.0,NaN,anthony69@hotmail.com,001-080-715-5689x268,Chennai,Financ,146215,2017-12-17,16.0,5,10018.0,Hyderabad,29.0,onsite
2,10743,Jeanette Hooper,41.0,M,gutierrezzachary@gmail.com,1139018681,Bangalore,IT,124286,2018-02-08,2.0,Good,10071.0,Delhi,22.0,remote
3,19229,Jesse Stewart,39.0,NaN,kmartinez@hotmail.com,+1-108-550-5011x4112,delhi,IT,111413,2018-04-07,14.0,Poor,10042.0,NaN,29.0,Remote
4,12385,William Maxwell,19.0,Male,shortjay@abc.org,050.572.6766,delhi,Financ,99001,2024-10-19,11.0,NaN,10094.0,Bangalore,16.0,onsite
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6076,18150,Kevin Campbell,24.0,female,marcowright@gmail.com,001-662-677-1946x18388,mumbai,Finance,148166,2021-11-16,5.0,Poor,10020.0,Hyderabad,29.0,Onsite
6077,15492,Richard Garcia,37.0,male,wgonzalez@yahoo.com,003.857.8489x4984,Bangalore,HR,41558,2021-03-08,3.0,2,10082.0,Bangalor,27.0,Hybrid
6078,18233,Richard Rodriguez,48.0,NaN,wrose@ortiz-wong.com,001-311-370-6322x0556,Chennai,HR,39682,2023-06-08,20.0,3,10071.0,Hyderabad,27.0,remote
6079,14157,Lucas Ramsey,18.0,NaN,cgreen@peters-reyes.info,326.539.9841,Mmbai,NaN,127574.42,2024-06-16,9.0,Poor,10024.0,Mmbai,1.0,Remote
6080,10656,Leslie Hansen,21.0,NaN,j,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [560]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df['Age'] = df['Age'].astype(int)

In [561]:
df['Age'].unique()

array([ 39,  31,  41,  19,  56,  62,  63,  20,  51,  38,  33,  53,  44,
        48,  26,  43,  47,  28,  40,  35,  55,  42,  45,  54,  64,  29,
        57,  32,  27,  37,  25,  21,  30,  18,  59,  34,  61,  22,  49,
        58,  24,  65,  46, 200,  60,  36,  50, 150,  52,  23, 101])

In [562]:
df[df['Age'] == 'NaN']

Empty DataFrame
Columns: [ID, Name, Age, Gender, Email, Phone_Number, City, Department, Salary, Joining_Date, Experience_Years, Performance_Score, Manager_ID, Work_Location, Bonus_Percentage, Remote_Onsite]
Index: []

In [563]:
# Q1 = df['Age'].quantile(0.25)
# Q3 = df['Age'].quantile(0.75)

# IQR = Q3 - Q1

lower_limit = 18
upper_limit = 65

# print("Q1:", Q1)
# print("Q3:", Q3)
# print("Lower limit:", lower_limit)
# print("Upper limit:", upper_limit)

In [564]:
outliers = df[(df['Age'] < lower_limit) | (df['Age'] > upper_limit)]
print("\nOutliers found:")
print(outliers['Age'])

Outliers found:
91      200
170     150
218     200
475     101
546     200
570     101
762     200
911     101
961     150
1177    200
1203    200
1227    150
1333    101
1432    200
1523    150
1601    150
1829    150
1871    150
2115    200
2157    101
2394    200
2600    200
2705    101
3016    200
3123    150
3334    200
3421    150
3437    101
3472    101
3500    150
3720    101
3876    150
4019    200
4140    101
4143    101
4176    101
4376    200
4409    200
4633    200
4754    150
4994    150
5045    101
5211    101
5281    150
5302    200
5328    200
5368    150
5552    101
5575    200
5597    150
5599    200
5672    101
5797    200
5861    200
5897    150
Name: Age, dtype: int64

In [565]:
median_age = df['Age'].median()
df.loc[(df['Age'] < lower_limit) | (df['Age'] > upper_limit), 'Age'] = median_age

df['Age'] = df['Age'].astype(int)

In [566]:
df['Age'].unique()

array([39, 31, 41, 19, 56, 62, 63, 20, 51, 38, 33, 53, 44, 48, 26, 43, 47,
       28, 40, 35, 55, 42, 45, 54, 64, 29, 57, 32, 27, 37, 25, 21, 30, 18,
       59, 34, 61, 22, 49, 58, 24, 65, 46, 60, 36, 50, 52, 23])

In [567]:
df['Gender'].unique()

array([nan, 'M', 'Male', 'F', 'Unknown', 'Female', 'female', 'male'],
      dtype=object)

In [568]:
df['Gender'] = df['Gender'].str.lower()
df['Gender'].value_counts()

Gender
male       1546
female     1484
m           770
f           754
unknown     737
Name: count, dtype: int64

In [569]:
df['Gender'] = df['Gender'].replace({
    'm' : 'male',
    'f' : 'female'
})

In [570]:
df['Gender'].unique()

array([nan, 'male', 'female', 'unknown'], dtype=object)

In [571]:
df['Gender'] = df['Gender'].replace('nan',np.nan)
df['Gender'].isnull().sum()

np.int64(784)

In [572]:
df['Gender'].value_counts()

Gender
male       2316
female     2238
unknown     737
Name: count, dtype: int64

In [573]:
df['Gender'] = df['Gender'].fillna('unknown')

In [574]:
df['Gender'].value_counts()

Gender
male       2316
female     2238
unknown    1521
Name: count, dtype: int64

In [575]:
df['Email'].unique()

array(['santanaheidi@simpson.com', 'anthony69@hotmail.com',
       'gutierrezzachary@gmail.com', ..., 'wrose@ortiz-wong.com',
       'cgreen@peters-reyes.info', 'j'], dtype=object)

In [576]:
df['Email'] = df['Email'].str.strip()
df['Email'] = df['Email'].str.lower()

In [577]:
df[df['Email'].str.contains('@',na=False)]

,ID,Name,Age,Gender,Email,Phone_Number,City,Department,Salary,Joining_Date,Experience_Years,Performance_Score,Manager_ID,Work_Location,Bonus_Percentage,Remote_Onsite
0,16271,Morgan Reyes,39,unknown,santanaheidi@simpson.com,862.555.7437x566,delhi,Financ,104695.6,2019-05-09,12.0,1,10002.0,Chennai,18.0,Onsite
1,12235,Brendan Thomas,31,unknown,anthony69@hotmail.com,001-080-715-5689x268,Chennai,Financ,146215,2017-12-17,16.0,5,10018.0,Hyderabad,29.0,onsite
2,10743,Jeanette Hooper,41,male,gutierrezzachary@gmail.com,1139018681,Bangalore,IT,124286,2018-02-08,2.0,Good,10071.0,Delhi,22.0,remote
3,19229,Jesse Stewart,39,unknown,kmartinez@hotmail.com,+1-108-550-5011x4112,delhi,IT,111413,2018-04-07,14.0,Poor,10042.0,NaN,29.0,Remote
4,12385,William Maxwell,19,male,shortjay@abc.org,050.572.6766,delhi,Financ,99001,2024-10-19,11.0,NaN,10094.0,Bangalore,16.0,onsite
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6075,13841,Jennifer Myers,45,unknown,phillipnguyen@schmidt.com,3387533178,NaN,IT,1062909,2023-02-19,10.0,Good,10068.0,NaN,3.0,Hybrid
6076,18150,Kevin Campbell,24,female,marcowright@gmail.com,001-662-677-1946x18388,mumbai,Finance,148166,2021-11-16,5.0,Poor,10020.0,Hyderabad,29.0,Onsite
6077,15492,Richard Garcia,37,male,wgonzalez@yahoo.com,003.857.8489x4984,Bangalore,HR,41558,2021-03-08,3.0,2,10082.0,Bangalor,27.0,Hybrid
6078,18233,Richard Rodriguez,48,unknown,wrose@ortiz-wong.com,001-311-370-6322x0556,Chennai,HR,39682,2023-06-08,20.0,3,10071.0,Hyderabad,27.0,remote
6079,14157,Lucas Ramsey,18,unknown,cgreen@peters-reyes.info,326.539.9841,Mmbai,NaN,127574.42,2024-06-16,9.0,Poor,10024.0,Mmbai,1.0,Remote

In [578]:
df[df['Email'].str.count('@') == 1]

,ID,Name,Age,Gender,Email,Phone_Number,City,Department,Salary,Joining_Date,Experience_Years,Performance_Score,Manager_ID,Work_Location,Bonus_Percentage,Remote_Onsite
0,16271,Morgan Reyes,39,unknown,santanaheidi@simpson.com,862.555.7437x566,delhi,Financ,104695.6,2019-05-09,12.0,1,10002.0,Chennai,18.0,Onsite
1,12235,Brendan Thomas,31,unknown,anthony69@hotmail.com,001-080-715-5689x268,Chennai,Financ,146215,2017-12-17,16.0,5,10018.0,Hyderabad,29.0,onsite
2,10743,Jeanette Hooper,41,male,gutierrezzachary@gmail.com,1139018681,Bangalore,IT,124286,2018-02-08,2.0,Good,10071.0,Delhi,22.0,remote
3,19229,Jesse Stewart,39,unknown,kmartinez@hotmail.com,+1-108-550-5011x4112,delhi,IT,111413,2018-04-07,14.0,Poor,10042.0,NaN,29.0,Remote
4,12385,William Maxwell,19,male,shortjay@abc.org,050.572.6766,delhi,Financ,99001,2024-10-19,11.0,NaN,10094.0,Bangalore,16.0,onsite
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6075,13841,Jennifer Myers,45,unknown,phillipnguyen@schmidt.com,3387533178,NaN,IT,1062909,2023-02-19,10.0,Good,10068.0,NaN,3.0,Hybrid
6076,18150,Kevin Campbell,24,female,marcowright@gmail.com,001-662-677-1946x18388,mumbai,Finance,148166,2021-11-16,5.0,Poor,10020.0,Hyderabad,29.0,Onsite
6077,15492,Richard Garcia,37,male,wgonzalez@yahoo.com,003.857.8489x4984,Bangalore,HR,41558,2021-03-08,3.0,2,10082.0,Bangalor,27.0,Hybrid
6078,18233,Richard Rodriguez,48,unknown,wrose@ortiz-wong.com,001-311-370-6322x0556,Chennai,HR,39682,2023-06-08,20.0,3,10071.0,Hyderabad,27.0,remote
6079,14157,Lucas Ramsey,18,unknown,cgreen@peters-reyes.info,326.539.9841,Mmbai,NaN,127574.42,2024-06-16,9.0,Poor,10024.0,Mmbai,1.0,Remote

In [579]:
df['Email_Domain'] = df['Email'].str.split('@').str[-1]

In [580]:
df['Email_Domain'].unique()

array(['simpson.com', 'hotmail.com', 'gmail.com', ..., 'ortiz-wong.com',
       'peters-reyes.info', 'j'], dtype=object)

In [581]:
df['Email_Domain'].value_counts().head(50)

Email_Domain
gmail.com           1005
yahoo.com            991
hotmail.com          954
smith.com             32
johnson.com           29
company.com           25
williams.com          21
brown.com             17
test.net              15
outlook.com           14
miller.com            14
davis.com             12
thompson.com          12
                      12
rodriguez.com         11
user#domain.com       11
perez.com             11
garcia.com            10
lopez.com              9
user.domain..com       9
jones.com              9
thomas.com             9
white.com              9
lee.com                8
martinez.com           8
abc.org                7
green.com              7
hernandez.com          7
gonzalez.com           7
sanchez.com            7
gomez.com              6
hall.com               6
nelson.com             6
torres.com             6
hill.com               6
ross.com               6
wilson.com             6
hart.com               6
bailey.com             6
rogers.com             6
anderson.com           6
harris.com             6
martin.com             6
baker.com              6
sullivan.com           5
butler.com             5
cox.com                5
robinson.com           5
gutierrez.com          5
johnson.biz            5
Name: count, dtype: int64

In [582]:
df = df[df['Email_Domain'] != 'j']
df['Email_Domain'].unique()

array(['simpson.com', 'hotmail.com', 'gmail.com', ...,
       'peters-mitchell.net', 'ortiz-wong.com', 'peters-reyes.info'],
      dtype=object)

In [583]:
df.loc[:, 'Email_Domain'] = df['Email_Domain'].str.replace('#', '', regex=False)
df.loc[:, 'Email_Domain'] = df['Email_Domain'].str.replace('-', '', regex=False)

df['Email_Domain']

0            simpson.com
1            hotmail.com
2              gmail.com
3            hotmail.com
4                abc.org
              ...
6075         schmidt.com
6076           gmail.com
6077           yahoo.com
6078       ortizwong.com
6079    petersreyes.info
Name: Email_Domain, Length: 6074, dtype: object

In [584]:
df.loc[:, 'Email_Domain'] = df['Email_Domain'].fillna('unknown.com')

In [585]:
df.loc[:,'Email_Domain'] = df['Email_Domain'].replace({
    'gamil.com': 'gmail.com',
    'yahooo.com': 'yahoo.com'
})

In [586]:
df.loc[:, 'Email_Domain'] = df['Email_Domain'].replace('nan',np.nan)

In [587]:
counts = df['Email_Domain'].value_counts()

rare_domains = counts[counts < 50].index

# create Domain column first
df['Domain'] = df['Email_Domain'].replace(rare_domains, 'Others')

# now fill missing using mode (MOST COMMON VALUE)
df['Domain'] = df['Domain'].fillna(df['Domain'].mode()[0])

# check missing values
df['Domain'].isna().sum()

C:\Users\KIIT\AppData\Local\Temp\ipykernel_18692\3609360788.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Domain'] = df['Email_Domain'].replace(rare_domains, 'Others')
C:\Users\KIIT\AppData\Local\Temp\ipykernel_18692\3609360788.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Domain'] = df['Domain'].fillna(df['Domain'].mode()[0])

np.int64(0)

In [588]:
# # Replace rare email domains with "Others" and fill missing using mode

# # 1️⃣ Count domain frequency
# domain_counts = df['Email_Domain'].value_counts()

# # 2️⃣ Define rare domains (change threshold if needed)
# rare_domains = domain_counts[domain_counts < 20].index

# # 3️⃣ Replace rare domains with "Others"
# df['Domain'] = df['Email_Domain'].replace(rare_domains, 'Others')

# # 4️⃣ Fill missing values using mode
# mode_domain = df['Domain'].mode()[0]
# df['Domain'].fillna(mode_domain, inplace=True)

# # 5️⃣ Check result
# df['Domain'].value_counts()

In [589]:
free_domains = ['gmail.com','yahoo.com','hotmail.com']
df.loc[:,'Email_Type'] = df['Email_Domain'].apply(lambda x: 'personal' if x in free_domains else 'corporate')

C:\Users\KIIT\AppData\Local\Temp\ipykernel_18692\530516958.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:,'Email_Type'] = df['Email_Domain'].apply(lambda x: 'personal' if x in free_domains else 'corporate')

In [590]:
corporate_users = df[df['Email_Type'] == 'corporate']
corporate_users

,ID,Name,Age,Gender,Email,Phone_Number,City,Department,Salary,Joining_Date,Experience_Years,Performance_Score,Manager_ID,Work_Location,Bonus_Percentage,Remote_Onsite,Email_Domain,Domain,Email_Type
0,16271,Morgan Reyes,39,unknown,santanaheidi@simpson.com,862.555.7437x566,delhi,Financ,104695.6,2019-05-09,12.0,1,10002.0,Chennai,18.0,Onsite,simpson.com,Others,corporate
4,12385,William Maxwell,19,male,shortjay@abc.org,050.572.6766,delhi,Financ,99001,2024-10-19,11.0,NaN,10094.0,Bangalore,16.0,onsite,abc.org,Others,corporate
5,19314,Rachel Shelton,56,female,carpenterian@keller.com,(584)676-7314x00733,Mmbai,Marketing,83979,2022-09-05,10.0,Excellent,10067.0,Mmbai,14.0,NaN,keller.com,Others,corporate
7,13566,Colin Robinson,62,female,stanleyamy@clay.com,(028)169-3023,delhi,IT,56741,2022-03-20,7.0,3,10016.0,Mumbai,NaN,Remote,clay.com,Others,corporate
9,17069,Nichole Garcia,20,unknown,NaN,268.737.4111x44696,Bangalor,Operations,NaN,2017-11-21,20.0,NaN,10020.0,Bangalore,14.0,Hybrid,unknown.com,unknown.com,corporate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6070,15200,Kirk Quinn,57,unknown,vmunoz@arellano.org,(067)865-8832x748,mumbai,hr,35392,03/01/2022,12.0,Excellent,10075.0,Delhi,18.0,Hybrid,arellano.org,Others,corporate
6073,11222,Mark Beltran,58,female,thomasallen@peters-mitchell.net,468-601-5918x560,delhi,Operations,31650,2022-06-30,13.0,Good,10067.0,Bangalor,27.0,onsite,petersmitchell.net,Others,corporate
6075,13841,Jennifer Myers,45,unknown,phillipnguyen@schmidt.com,3387533178,NaN,IT,1062909,2023-02-19,10.0,Good,10068.0,NaN,3.0,Hybrid,schmidt.com,Others,corporate
6078,18233,Richard Rodriguez,48,unknown,wrose@ortiz-wong.com,001-311-370-6322x0556,Chennai,HR,39682,2023-06-08,20.0,3,10071.0,Hyderabad,27.0,remote,ortizwong.com,Others,corporate
6079,14157,Lucas Ramsey,18,unknown,cgreen@peters-reyes.info,326.539.9841,Mmbai,NaN,127574.42,2024-06-16,9.0,Poor,10024.0,Mmbai,1.0,Remote,petersreyes.info,Others,corporate

In [591]:
corporate_users['Email_Type'].value_counts()

Email_Type
corporate    3124
Name: count, dtype: int64

In [592]:
df['Phone_Number'].value_counts().head(20)

Phone_Number
12345                     19
+91 9876543210            18
987 654 3210              17
abcdef                    15
001-019-194-2744x70938     1
528-203-6578               1
+1-015-044-2363x77489      1
+1-111-921-9455x028        1
326.539.9841               1
862.555.7437x566           1
001-080-715-5689x268       1
1139018681                 1
+1-108-550-5011x4112       1
050.572.6766               1
(584)676-7314x00733        1
965.752.9562x446           1
(028)169-3023              1
001-056-326-2176           1
001-411-146-9146x858       1
+1-772-724-5074x348        1
Name: count, dtype: int64

In [593]:
df['cleaned_phone'] = df['Phone_Number'].astype(str).str.replace(r'\D', '', regex=True)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_18692\3408928148.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cleaned_phone'] = df['Phone_Number'].astype(str).str.replace(r'\D', '', regex=True)

In [594]:
def get_country_code(number):
    if pd.isnull(number):
        return np.nan
    if len(number) <= 10:
        return np.nan
    return number[:-10]

df.loc[:,'Country_code'] = df['cleaned_phone'].apply(get_country_code)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_18692\3464890989.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:,'Country_code'] = df['cleaned_phone'].apply(get_country_code)

In [595]:
df['Country_code'].isnull().sum()

np.int64(1996)

In [596]:
def get_local_number(number):
    if pd.isnull(number) or len(number) < 10:
        return np.nan
    return number[-10:]
df['Local_number'] = df['cleaned_phone'].apply(get_local_number)

C:\Users\KIIT\AppData\Local\Temp\ipykernel_18692\1939632110.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Local_number'] = df['cleaned_phone'].apply(get_local_number)

In [599]:
df['Is_Valid_number'] = df['Local_number'].notnull()

C:\Users\KIIT\AppData\Local\Temp\ipykernel_18692\3777407187.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Is_Valid_number'] = df['Local_number'].notnull()

In [601]:
df['Salary'].value_counts()

Salary
129159     3
92399      3
61269      2
53147      2
140248     2
          ..
97914      1
1062909    1
148166     1
39682      1
83979      1
Name: count, Length: 5880, dtype: int64

In [602]:
df['Salary'].isnull().sum()

np.int64(54)

In [605]:
salary_series = df['Salary']
salary_str = salary_series.astype(str).str.strip()
unique_salaries = salary_str.unique()

In [607]:


def salary_format_type(s):
    s = str(s).strip()

    if s.lower() == 'nan':
        return 'Missing'

    elif any(c.isalpha() for c in s):
        return 'Contains letters (k, M, etc.)'

    elif any(c in '₹$,' for c in s):
        return 'Currency/Comma'

    elif s.replace('.', '', 1).isdigit():
        return 'Numeric'

    else:
        return 'Other/Invalid'


# Apply on Salary column
Salary_format = df['Salary'].apply(salary_format_type)

# Count each type
Salary_format.value_counts()

Salary
Numeric           5967
Missing             54
Currency/Comma      53
Name: count, dtype: int64

In [609]:
currency_comma_mask = salary_str.str.contains(r'[$₹€]', regex=True, na=False)
currency_comma_mask

0       False
1       False
2       False
3       False
4       False
        ...
6075    False
6076    False
6077    False
6078    False
6079    False
Name: Salary, Length: 6074, dtype: bool

In [610]:
unique_currency_comma = salary_str[currency_comma_mask].unique()
unique_currency_comma

array(['₹102348', '₹125315', '₹175543', '₹137382', '₹187279', '₹139612',
       '₹113686', '₹156506', '₹49253', '₹166869', '₹176030', '₹198546',
       '₹37878', '₹33159', '₹60766', '₹43517', '₹39918', '₹59994',
       '₹78153', '₹49741', '₹45280', '₹34340', '₹182322', '₹133002',
       '₹153803', '₹131721', '₹57893', '₹117997', '₹70227', '₹80991',
       '₹41307', '₹117318', '₹58272', '₹82455', '₹193203', '₹173992',
       '₹84693', '₹181899', '₹44298', '₹31609', '₹198427', '₹124475',
       '₹63535', '₹79553', '₹125560', '₹60472', '₹138030', '₹89483',
       '₹185699', '₹118298', '₹30686', '₹62460', '₹45846'], dtype=object)

In [611]:
print('Total unique salary/comma formats:', len(unique_currency_comma))
print('Sample unique currency/comma formats:')
print(unique_currency_comma[:53])

Total unique salary/comma formats: 53
Sample unique currency/comma formats:
['₹102348' '₹125315' '₹175543' '₹137382' '₹187279' '₹139612' '₹113686'
 '₹156506' '₹49253' '₹166869' '₹176030' '₹198546' '₹37878' '₹33159'
 '₹60766' '₹43517' '₹39918' '₹59994' '₹78153' '₹49741' '₹45280' '₹34340'
 '₹182322' '₹133002' '₹153803' '₹131721' '₹57893' '₹117997' '₹70227'
 '₹80991' '₹41307' '₹117318' '₹58272' '₹82455' '₹193203' '₹173992'
 '₹84693' '₹181899' '₹44298' '₹31609' '₹198427' '₹124475' '₹63535'
 '₹79553' '₹125560' '₹60472' '₹138030' '₹89483' '₹185699' '₹118298'
 '₹30686' '₹62460' '₹45846']

In [ ]:
df['Salary'] = df['Salary'].astype(str).str.replace('₹','',regex=True)